begin;
select plan(13);
select has_table('public','pages','pages exists');
select has_table('public','content_revisions','revision history exists');
select has_function('public','search_public_content',array['text','text','integer','integer'],'public search exists');
select policies_are('public','pages',array['public_published_pages'],'pages has an explicit read policy');
select policies_are('public','content_revisions',array['admin_revisions'],'revisions are admin only');
select ok((select relrowsecurity from pg_class where oid='public.pages'::regclass),'RLS enabled on pages');
select ok((select public from storage.buckets where id='public-media'),'public media bucket exists');
select is((select count(*)::int from public.pages),11,'all fixed pages are seeded');
select function_privs_are('public','is_active_admin',array[]::text[], 'anon', array['EXECUTE'], 'anon may evaluate the admin helper in published-content RLS');
select has_view('public','public_navigation_items','public navigation view exists');
set local role anon;
select is((select count(*)::int from public.public_navigation_items),10,'anon sees all visible fixed navigation routes');
reset role;
select is((select count(*)::int from public.public_documents),1,'seed document is publicly listed after verified upload');
select is((select count(*)::int from public.public_pages where page_key='documents'),1,'documents CMS page is published');
select * from finish();
rollback;
