import { useEffect, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { confirmDiscard, useUnsavedChanges } from './useUnsavedChanges';
import { AdminLoading, AdminNotice, type NoticeTone } from './AdminFeedback';
import { useSaveShortcut } from './useAdminShortcuts';

type NavItem = { id?: string; label: string; target_page_key: string | null; external_url: string | null; sort_order: number; visible: boolean };
type Page = { page_key: string; title: string; slug: string };
async function saveItem(client: SupabaseClient, payload: NavItem) { const { data, error } = await client.functions.invoke('save-content', { body: { entity: 'navigation_items', payload } }); if (error) throw new Error(data?.error ?? error.message); return data.data; }

export default function NavigationManager({ client }: { client: SupabaseClient }) {
  const [items, setItems] = useState<NavItem[]>([]); const [pages, setPages] = useState<Page[]>([]); const [baseline, setBaseline] = useState(''); const [deletedIds, setDeletedIds] = useState<string[]>([]); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [dragged, setDragged] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [tone, setTone] = useState<NoticeTone>('info');
  const dirty = Boolean(baseline && (JSON.stringify(items) !== baseline || deletedIds.length)); useUnsavedChanges(dirty);
  const load = async () => { const [{ data: nav, error }, { data: pageRows }] = await Promise.all([client.from('navigation_items').select('*').order('sort_order'), client.from('pages').select('page_key,title,slug').order('title')]); if (error) { setTone('error'); setMessage('Navigationen kunde inte hämtas. Försök igen.'); setLoading(false); return; } setItems(nav ?? []); setPages(pageRows ?? []); setBaseline(JSON.stringify(nav ?? [])); setDeletedIds([]); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const update = (index: number, patch: Partial<NavItem>) => setItems(items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const move = (from: number, to: number) => { const copy = [...items]; const [item] = copy.splice(from, 1); copy.splice(to, 0, item); setItems(copy); };
  const remove = (index: number) => { const item = items[index]; if (item.id) setDeletedIds([...deletedIds, item.id]); setItems(items.filter((_, itemIndex) => itemIndex !== index)); };
  const save = async () => { setSaving(true); setTone('info'); setMessage('Sparar navigationen…'); try { if (items.some((item) => !item.label.trim() || Boolean(item.target_page_key) === Boolean(item.external_url))) throw new Error('Varje länk måste ha en etikett och exakt ett länkmål.'); for (const [index, item] of items.entries()) await saveItem(client, { ...item, sort_order: index }); for (const id of deletedIds) { const { data, error } = await client.functions.invoke('manage-navigation', { body: { id, action: 'delete' } }); if (error) throw new Error(data?.error ?? error.message); } setTone('success'); setMessage('Klart! Navigationen är publicerad och syns direkt.'); await load(); } catch (error) { setTone('error'); setMessage(error instanceof Error ? error.message : 'Navigationen kunde inte sparas.'); } finally { setSaving(false); } };
  const add = () => setItems([...items, { label: 'Ny länk', target_page_key: pages[0]?.page_key ?? null, external_url: null, sort_order: items.length, visible: true }]);
  useSaveShortcut(dirty && !saving, save);
  if (loading) return <AdminLoading label="Hämtar navigationen" />;
  return <section className="admin-panel navigation-manager"><div className="admin-heading editor-toolbar"><div><p className="eyebrow">Webbplatsens menyer</p><h1>Navigation</h1><p>Ordningen här är samma som på webbplatsen.</p></div><div className="admin-actions">{dirty && <span className="dirty-badge"><i className="ph ph-pencil-simple" aria-hidden="true" />Osparat</span>}<button className="button button-secondary" type="button" onClick={add}><i className="ph ph-plus" aria-hidden="true" />Lägg till länk</button><button className="button button-primary" disabled={!dirty || saving} onClick={save} title="Spara (Ctrl+S)"><i className="ph ph-floppy-disk" aria-hidden="true" />{saving ? 'Sparar…' : 'Spara'}</button></div></div>
    <AdminNotice message={message} tone={tone} onDismiss={() => setMessage('')} /><div className="navigation-editor-list">{items.map((item, index) => { const external = Boolean(item.external_url); return <article draggable className={dragged === index ? 'is-dragging' : ''} key={item.id ?? `new-${index}`} onDragStart={() => setDragged(index)} onDragEnd={() => setDragged(null)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragged !== null && dragged !== index) move(dragged, index); setDragged(null); }}><span className="drag-handle" aria-hidden="true">⋮⋮</span><label>Etikett<input value={item.label} onChange={(event) => update(index, { label: event.target.value })} /></label><label>Typ<select value={external ? 'external' : 'internal'} onChange={(event) => update(index, event.target.value === 'external' ? { target_page_key: null, external_url: 'https://' } : { target_page_key: pages[0]?.page_key ?? null, external_url: null })}><option value="internal">Intern sida</option><option value="external">Extern länk</option></select></label>{external ? <label>Webbadress<input type="url" value={item.external_url ?? ''} onChange={(event) => update(index, { external_url: event.target.value })} /></label> : <label>Sida<select value={item.target_page_key ?? ''} onChange={(event) => update(index, { target_page_key: event.target.value })}>{pages.map((page) => <option value={page.page_key} key={page.page_key}>{page.title} ({page.slug})</option>)}</select></label>}<label className="check compact-check"><input type="checkbox" checked={item.visible} onChange={(event) => update(index, { visible: event.target.checked })} /> Synlig</label><button type="button" className="icon-button danger" aria-label={`Ta bort ${item.label}`} onClick={() => remove(index)}><i className="ph ph-trash" aria-hidden="true" /></button></article>; })}</div>
    <div className="navigation-preview"><strong>Menyförhandsvisning</strong>{items.filter((item) => item.visible).map((item) => <span key={item.id ?? item.label}>{item.label}</span>)}</div><button type="button" className="text-button" disabled={!dirty} onClick={() => { if (confirmDiscard(dirty)) void load(); }}>Återställ osparade ändringar</button>
  </section>;
}
