import type { EditorNode } from '../../lib/cms/schema';
import RichTextEditor from './RichTextEditor';

type ImageValue={src:string;alt:string;decorative?:boolean;crop?:'original'|'square'|'landscape'|'portrait'|'wide';focusX?:number;focusY?:number};
type Props={node:EditorNode;onChange:(node:EditorNode)=>void};

function ImageFields({value,onChange}:{value:ImageValue;onChange:(value:ImageValue)=>void}){return <fieldset className="inspector-group"><legend>Bild</legend><label>Bildadress<input value={value.src} onChange={event=>onChange({...value,src:event.target.value})}/></label><label className="check"><input type="checkbox" checked={value.decorative??false} onChange={event=>onChange({...value,decorative:event.target.checked,alt:event.target.checked?'':value.alt})}/>Dekorativ bild</label>{!value.decorative&&<label>Alternativtext<input value={value.alt} maxLength={240} onChange={event=>onChange({...value,alt:event.target.value})}/></label>}<label>Bildförhållande<select value={value.crop??'original'} onChange={event=>onChange({...value,crop:event.target.value as ImageValue['crop']})}><option value="original">Original</option><option value="square">Kvadrat</option><option value="landscape">Liggande</option><option value="portrait">Stående</option><option value="wide">Bred</option></select></label><label>Fokus vågrätt<input type="range" min="0" max="1" step="0.01" value={value.focusX??.5} onChange={event=>onChange({...value,focusX:Number(event.target.value)})}/></label><label>Fokus lodrätt<input type="range" min="0" max="1" step="0.01" value={value.focusY??.5} onChange={event=>onChange({...value,focusY:Number(event.target.value)})}/></label></fieldset>}
function LinkFields({label,href,onChange}:{label:string;href:string;onChange:(value:{label:string;href:string})=>void}){return <div className="inspector-link"><label>Etikett<input value={label} onChange={event=>onChange({label:event.target.value,href})}/></label><label>Länk<input value={href} onChange={event=>onChange({label,href:event.target.value})}/></label></div>}

export default function NodeInspector({node,onChange}:Props){
  const update=(patch:Record<string,unknown>)=>onChange({...node,...patch} as EditorNode);
  if(node.type==='component_instance')return <div className="inspector-fields"><p><strong>Synkad komponent</strong></p><p>Endast exponerade instansegenskaper kan ändras.</p>{Object.entries(node.properties).map(([key,value])=><label key={key}>{key}<input value={typeof value==='string'?value:JSON.stringify(value)} onChange={event=>onChange({...node,properties:{...node.properties,[key]:event.target.value}})}/></label>)}</div>;
  if(node.type==='hero')return <div className="inspector-fields"><label>Huvudrubrik<input value={node.heading} maxLength={160} onChange={event=>update({heading:event.target.value})}/></label><label>Ingress<textarea value={node.text} maxLength={500} onChange={event=>update({text:event.target.value})}/></label>{node.image?<ImageFields value={node.image} onChange={image=>update({image})}/>:<button type="button" onClick={()=>update({image:{src:'/images/smedby-area-overview.webp',alt:'Smedby 1:6'}})}>Lägg till bild</button>}{node.action?<fieldset className="inspector-group"><legend>Knapp</legend><LinkFields {...node.action} onChange={action=>update({action})}/><button type="button" onClick={()=>{const {action:_action,...rest}=node;onChange(rest as EditorNode)}}>Ta bort knapp</button></fieldset>:<button type="button" onClick={()=>update({action:{label:'Läs mer',href:'/'}})}>Lägg till knapp</button>}</div>;
  if(node.type==='rich_text')return <div className="inspector-fields"><label>Avsnittsrubrik<input value={node.heading??''} onChange={event=>update({heading:event.target.value||undefined})}/></label><RichTextEditor value={node.document} onChange={document=>update({document})}/></div>;
  if(node.type==='notice')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Text<textarea value={node.text} onChange={event=>update({text:event.target.value})}/></label><label>Ton<select value={node.tone} onChange={event=>update({tone:event.target.value})}><option value="info">Information</option><option value="warning">Varning</option><option value="success">Positiv</option></select></label></div>;
  if(node.type==='image_text')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Text<textarea value={node.text} onChange={event=>update({text:event.target.value})}/></label><ImageFields value={node.image} onChange={image=>update({image})}/><label>Bildplacering<select value={node.imagePosition} onChange={event=>update({imagePosition:event.target.value})}><option value="left">Vänster</option><option value="right">Höger</option></select></label></div>;
  if(node.type==='card_grid')return <div className="inspector-fields"><label>Avsnittsrubrik<input value={node.heading??''} onChange={event=>update({heading:event.target.value||undefined})}/></label>{node.cards.map((card,index)=><fieldset className="inspector-group" key={index}><legend>Kort {index+1}</legend><label>Rubrik<input value={card.title} onChange={event=>update({cards:node.cards.map((item,itemIndex)=>itemIndex===index?{...item,title:event.target.value}:item)})}/></label><label>Text<textarea value={card.text} onChange={event=>update({cards:node.cards.map((item,itemIndex)=>itemIndex===index?{...item,text:event.target.value}:item)})}/></label>{card.link&&<LinkFields {...card.link} onChange={link=>update({cards:node.cards.map((item,itemIndex)=>itemIndex===index?{...item,link}:item)})}/>}<button type="button" disabled={node.cards.length===1} onClick={()=>update({cards:node.cards.filter((_,itemIndex)=>itemIndex!==index)})}>Ta bort kort</button></fieldset>)}<button type="button" disabled={node.cards.length>=12} onClick={()=>update({cards:[...node.cards,{title:'Nytt kort',text:'Beskrivning'}]})}>Lägg till kort</button></div>;
  if(node.type==='link_list')return <div className="inspector-fields"><label>Rubrik<input value={node.heading??''} onChange={event=>update({heading:event.target.value||undefined})}/></label>{node.links.map((link,index)=><fieldset className="inspector-group" key={index}><legend>Länk {index+1}</legend><LinkFields {...link} onChange={value=>update({links:node.links.map((item,itemIndex)=>itemIndex===index?value:item)})}/><button type="button" disabled={node.links.length===1} onClick={()=>update({links:node.links.filter((_,itemIndex)=>itemIndex!==index)})}>Ta bort länk</button></fieldset>)}<button type="button" onClick={()=>update({links:[...node.links,{label:'Ny länk',href:'/'}]})}>Lägg till länk</button></div>;
  if(node.type==='area_guide')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Text<textarea value={node.text} onChange={event=>update({text:event.target.value})}/></label>{node.image?<><ImageFields value={node.image} onChange={image=>update({image})}/><button type="button" onClick={()=>{const {image:_image,...rest}=node;onChange(rest as EditorNode)}}>Ta bort bild</button></>:<button type="button" onClick={()=>update({image:{src:'/images/smedby-area-overview.webp',alt:'Smedby 1:6'}})}>Lägg till bild</button>}{node.links.map((link,index)=><fieldset className="inspector-group" key={index}><legend>Länk {index+1}</legend><LinkFields {...link} onChange={value=>update({links:node.links.map((item,itemIndex)=>itemIndex===index?value:item)})}/><button type="button" onClick={()=>update({links:node.links.filter((_,itemIndex)=>itemIndex!==index)})}>Ta bort länk</button></fieldset>)}<button type="button" disabled={node.links.length>=12} onClick={()=>update({links:[...node.links,{label:'Ny plats',href:'/kontakt/'}]})}>Lägg till länk</button></div>;
  if(node.type==='faq')return <div className="inspector-fields"><label>Rubrik<input value={node.heading??''} onChange={event=>update({heading:event.target.value||undefined})}/></label>{node.items.map((item,index)=><fieldset className="inspector-group" key={index}><legend>Fråga {index+1}</legend><label>Fråga<input value={item.question} onChange={event=>update({items:node.items.map((value,itemIndex)=>itemIndex===index?{...value,question:event.target.value}:value)})}/></label><label>Svar<textarea value={item.answer} onChange={event=>update({items:node.items.map((value,itemIndex)=>itemIndex===index?{...value,answer:event.target.value}:value)})}/></label><button type="button" disabled={node.items.length===1} onClick={()=>update({items:node.items.filter((_,itemIndex)=>itemIndex!==index)})}>Ta bort fråga</button></fieldset>)}<button type="button" onClick={()=>update({items:[...node.items,{question:'Ny fråga',answer:'Svar'}]})}>Lägg till fråga</button></div>;
  if(node.type==='news_feed'||node.type==='calendar_feed')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Antal<input type="number" min="1" max="12" value={node.limit} onChange={event=>update({limit:Number(event.target.value)})}/></label></div>;
  if(node.type==='document_list')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Kategori<input value={node.category??''} onChange={event=>update({category:event.target.value||undefined})}/></label></div>;
  if(node.type==='search_teaser')return <div className="inspector-fields"><label>Rubrik<input value={node.heading} onChange={event=>update({heading:event.target.value})}/></label><label>Hjälptext<textarea value={node.text} onChange={event=>update({text:event.target.value})}/></label></div>;
  if(node.type==='heading')return <div className="inspector-fields"><label>Rubrik<input value={node.text} onChange={event=>update({text:event.target.value})}/></label><label>Nivå<select value={node.level} onChange={event=>update({level:Number(event.target.value)})}><option value="2">Rubrik 2</option><option value="3">Rubrik 3</option></select></label></div>;
  if(node.type==='image')return <div className="inspector-fields"><ImageFields value={node.image} onChange={image=>update({image})}/></div>;
  if(node.type==='button')return <div className="inspector-fields"><LinkFields label={node.label} href={node.href} onChange={value=>update(value)}/><label>Variant<select value={node.variant} onChange={event=>update({variant:event.target.value})}><option value="primary">Primär</option><option value="secondary">Sekundär</option><option value="text">Text</option></select></label></div>;
  if(node.type==='divider')return <label>Stil<select value={node.variant} onChange={event=>update({variant:event.target.value})}><option value="subtle">Diskret</option><option value="strong">Tydlig</option></select></label>;
  if(node.type==='spacer')return <label>Storlek<select value={node.size} onChange={event=>update({size:event.target.value})}><option value="small">Liten</option><option value="medium">Mellan</option><option value="large">Stor</option></select></label>;
  if(node.type==='approved_embed')return <div className="inspector-fields"><label>Titel<input value={node.title} onChange={event=>update({title:event.target.value})}/></label><label>Godkänd videoadress<input value={node.url} onChange={event=>update({url:event.target.value})}/></label><label>Bildförhållande<select value={node.aspect} onChange={event=>update({aspect:event.target.value})}><option value="16:9">16:9</option><option value="4:3">4:3</option></select></label></div>;
  return null;
}
