import { useState } from 'react';

export type PageSettings = { title:string; slug:string; seoTitle:string; seoDescription:string; socialMediaId:string|null };

export default function PageSettingsDialog({initial,busy,onClose,onSave}:{initial:PageSettings;busy:boolean;onClose:()=>void;onSave:(settings:PageSettings)=>Promise<void>}) {
  const [value,setValue]=useState(initial);
  const normalizedSlug=value.slug==='/'?'/':`/${value.slug.replace(/^\/+|\/+$/g,'')}/`;
  return <div className="page-settings-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="page-settings-dialog" role="dialog" aria-modal="true" aria-labelledby="page-settings-title"><div className="admin-heading"><div><p className="eyebrow">Sida och sökmotorer</p><h2 id="page-settings-title">Sidinställningar</h2></div><button type="button" aria-label="Stäng sidinställningar" onClick={onClose}>×</button></div><div className="inspector-fields"><label>Sidans titel<input autoFocus required maxLength={160} value={value.title} onChange={event=>setValue({...value,title:event.target.value})}/></label><label>Adress<input required pattern="/[a-z0-9\-/]*/" value={value.slug} onChange={event=>setValue({...value,slug:event.target.value.toLowerCase().replace(/[^a-z0-9\-/]/g,'-')})}/><small>Den gamla adressen börjar automatiskt hänvisa till den nya.</small></label><p>Ny adress: <code>{normalizedSlug}</code></p><label>SEO-titel<input maxLength={200} value={value.seoTitle} onChange={event=>setValue({...value,seoTitle:event.target.value})}/></label><label>Metabeskrivning<textarea maxLength={320} rows={4} value={value.seoDescription} onChange={event=>setValue({...value,seoDescription:event.target.value})}/></label></div><div className="dialog-actions"><button type="button" onClick={onClose}>Avbryt</button><button type="button" className="button button-primary" disabled={busy||!value.title.trim()||!normalizedSlug.match(/^\/[a-z0-9\-/]*\/$|^\/$/)} onClick={()=>void onSave({...value,slug:normalizedSlug})}>{busy?'Sparar…':'Spara inställningar'}</button></div></section></div>;
}
