import { useEffect, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { useUnsavedChanges } from './useUnsavedChanges';
import { AdminLoading, AdminNotice, CharacterCount, type NoticeTone } from './AdminFeedback';
import { useSaveShortcut } from './useAdminShortcuts';

type Settings = { id: true; site_name: string; contact_email: string | null; footer_text: string; default_seo_title: string; default_seo_description: string; social_media_id: string | null };
type Media = { id: string; original_name: string; storage_path: string; alt_text: string; public_url: string };

export default function SettingsManager({ client }: { client: SupabaseClient }) {
  const [value, setValue] = useState<Settings | null>(null); const [media, setMedia] = useState<Media[]>([]); const [baseline, setBaseline] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [tone, setTone] = useState<NoticeTone>('info');
  const dirty = Boolean(value && baseline && JSON.stringify(value) !== baseline); useUnsavedChanges(dirty);
  const load = async () => { const [{ data, error }, { data: mediaRows }] = await Promise.all([client.from('site_settings').select('*').single(), client.from('media_assets').select('id,original_name,storage_path,alt_text').is('deleted_at', null).like('mime_type', 'image/%').order('original_name')]); if (error) { setTone('error'); setMessage('Inställningarna kunde inte hämtas. Försök igen.'); setLoading(false); return; } setValue(data); setBaseline(JSON.stringify(data)); setMedia((mediaRows ?? []).map((item) => ({ ...item, public_url: client.storage.from('public-media').getPublicUrl(item.storage_path).data.publicUrl }))); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!value) return; setSaving(true); setTone('info'); setMessage('Sparar inställningarna…'); const { data, error } = await client.functions.invoke('save-content', { body: { entity: 'site_settings', payload: value } }); if (error) { setTone('error'); setMessage(data?.error ?? 'Inställningarna kunde inte sparas.'); } else { setValue(data.data); setBaseline(JSON.stringify(data.data)); setTone('success'); setMessage('Klart! Webbplatsinställningarna är publicerade.'); } setSaving(false); };
  useSaveShortcut(dirty && !saving, save);
  if (loading || !value) return <AdminLoading label="Hämtar webbplatsinställningar" />;
  const selectedImage = media.find((item) => item.id === value.social_media_id);
  return <section className="admin-panel settings-manager"><div className="admin-heading editor-toolbar"><div><p className="eyebrow">Hela webbplatsen</p><h1>Webbplatsinställningar</h1><p>Uppgifter som används på flera sidor.</p></div><div className="admin-actions">{dirty && <span className="dirty-badge"><i className="ph ph-pencil-simple" aria-hidden="true" />Osparat</span>}<button className="button button-primary" disabled={!dirty || saving} onClick={save} title="Spara (Ctrl+S)"><i className="ph ph-floppy-disk" aria-hidden="true" />{saving ? 'Sparar…' : 'Spara'}</button></div></div>
    <AdminNotice message={message} tone={tone} onDismiss={() => setMessage('')} /><div className="settings-layout"><div className="field-grid"><label>Webbplatsnamn<input value={value.site_name} maxLength={120} onChange={(event) => setValue({ ...value, site_name: event.target.value })} /><CharacterCount value={value.site_name} max={120} /></label><label>Kontaktadress<input type="email" value={value.contact_email ?? ''} onChange={(event) => setValue({ ...value, contact_email: event.target.value || null })} /></label><label className="span-two">Sidfotstext<textarea value={value.footer_text} maxLength={1000} onChange={(event) => setValue({ ...value, footer_text: event.target.value })} /><CharacterCount value={value.footer_text} max={1000} /></label><label>Standardtitel för SEO<input value={value.default_seo_title} maxLength={200} onChange={(event) => setValue({ ...value, default_seo_title: event.target.value })} /><CharacterCount value={value.default_seo_title} max={200} /></label><label>Standardbeskrivning för SEO<textarea value={value.default_seo_description} maxLength={320} onChange={(event) => setValue({ ...value, default_seo_description: event.target.value })} /><CharacterCount value={value.default_seo_description} max={320} /></label><label className="span-two">Standardbild vid delning<select value={value.social_media_id ?? ''} onChange={(event) => setValue({ ...value, social_media_id: event.target.value || null })}><option value="">Ingen standardbild</option>{media.map((item) => <option value={item.id} key={item.id}>{item.original_name}</option>)}</select><small>Används när en sida delas i sociala medier.</small></label></div>
      <aside className="settings-preview"><h2>Förhandsvisning</h2>{selectedImage && <img src={selectedImage.public_url} alt={selectedImage.alt_text} />}<div className="seo-preview"><span>Delning och sökresultat</span><strong>{value.default_seo_title}</strong><small>www.smedby1-6.se</small><p>{value.default_seo_description}</p></div><footer><strong>{value.site_name}</strong><p>{value.footer_text}</p>{value.contact_email && <a href={`mailto:${value.contact_email}`}>{value.contact_email}</a>}</footer></aside></div>
  </section>;
}
