import { useEffect, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { useUnsavedChanges } from './useUnsavedChanges';

type Settings = { id: true; site_name: string; contact_email: string | null; footer_text: string; default_seo_title: string; default_seo_description: string; social_media_id: string | null };
type Media = { id: string; original_name: string; storage_path: string; alt_text: string; public_url: string };

export default function SettingsManager({ client }: { client: SupabaseClient }) {
  const [value, setValue] = useState<Settings | null>(null); const [media, setMedia] = useState<Media[]>([]); const [baseline, setBaseline] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const dirty = Boolean(value && baseline && JSON.stringify(value) !== baseline); useUnsavedChanges(dirty);
  const load = async () => { const [{ data, error }, { data: mediaRows }] = await Promise.all([client.from('site_settings').select('*').single(), client.from('media_assets').select('id,original_name,storage_path,alt_text').is('deleted_at', null).like('mime_type', 'image/%').order('original_name')]); if (error) { setMessage('Inställningarna kunde inte hämtas.'); return; } setValue(data); setBaseline(JSON.stringify(data)); setMedia((mediaRows ?? []).map((item) => ({ ...item, public_url: client.storage.from('public-media').getPublicUrl(item.storage_path).data.publicUrl }))); };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!value) return; setSaving(true); const { data, error } = await client.functions.invoke('save-content', { body: { entity: 'site_settings', payload: value } }); if (error) setMessage(data?.error ?? 'Inställningarna kunde inte sparas.'); else { setValue(data.data); setBaseline(JSON.stringify(data.data)); setMessage('Webbplatsinställningarna är publicerade live.'); } setSaving(false); };
  if (!value) return <p>Laddar…</p>;
  const selectedImage = media.find((item) => item.id === value.social_media_id);
  return <section className="admin-panel settings-manager"><div className="admin-heading"><div><p className="eyebrow">Globalt innehåll</p><h1>Webbplatsinställningar</h1></div><div className="admin-actions">{dirty && <span className="dirty-badge">Osparade ändringar</span>}<button className="button button-primary" disabled={!dirty || saving} onClick={save}>{saving ? 'Sparar…' : 'Spara inställningar'}</button></div></div>
    {message && <p role="status" className="save-message">{message}</p>}<div className="settings-layout"><div className="field-grid"><label>Webbplatsnamn<input value={value.site_name} maxLength={120} onChange={(event) => setValue({ ...value, site_name: event.target.value })} /></label><label>Kontaktadress<input type="email" value={value.contact_email ?? ''} onChange={(event) => setValue({ ...value, contact_email: event.target.value || null })} /></label><label className="span-two">Sidfotstext<textarea value={value.footer_text} maxLength={1000} onChange={(event) => setValue({ ...value, footer_text: event.target.value })} /></label><label>Standardtitel för SEO<input value={value.default_seo_title} maxLength={200} onChange={(event) => setValue({ ...value, default_seo_title: event.target.value })} /></label><label>Standardbeskrivning för SEO<textarea value={value.default_seo_description} maxLength={320} onChange={(event) => setValue({ ...value, default_seo_description: event.target.value })} /></label><label className="span-two">Standardbild vid delning<select value={value.social_media_id ?? ''} onChange={(event) => setValue({ ...value, social_media_id: event.target.value || null })}><option value="">Ingen standardbild</option>{media.map((item) => <option value={item.id} key={item.id}>{item.original_name}</option>)}</select></label></div>
      <aside className="settings-preview"><h2>Förhandsvisning</h2>{selectedImage && <img src={selectedImage.public_url} alt={selectedImage.alt_text} />}<div className="seo-preview"><span>Delning och sökresultat</span><strong>{value.default_seo_title}</strong><small>www.smedby1-6.se</small><p>{value.default_seo_description}</p></div><footer><strong>{value.site_name}</strong><p>{value.footer_text}</p>{value.contact_email && <a href={`mailto:${value.contact_email}`}>{value.contact_email}</a>}</footer></aside></div>
  </section>;
}
