import type { ContentBlock } from './schema';
export type BlockDefinition = { label:string; description:string; icon:string; category:'Layout'|'Text'|'Media'|'Navigation'|'Dynamiskt innehåll'|'Återanvändbart'; variants:string[]; defaultValue:ContentBlock; qualityRules:string[] };
export const blockRegistry: Record<ContentBlock['type'],BlockDefinition> = {
  hero:{label:'Huvudsektion',description:'Sidans huvudrubrik och introduktion.',icon:'ph-image',category:'Layout',variants:['standard','bild'],defaultValue:{type:'hero',heading:'Ny huvudrubrik',text:'Skriv en kort introduktion.'},qualityRules:['Exakt en per sida']},
  rich_text:{label:'Text',description:'Formaterad brödtext.',icon:'ph-text-t',category:'Text',variants:['standard','smal'],defaultValue:{type:'rich_text',document:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Ny text'}]}]}},qualityRules:['Rubriknivå 2–3']},
  card_grid:{label:'Kort',description:'Länkade informationskort.',icon:'ph-squares-four',category:'Navigation',variants:['standard'],defaultValue:{type:'card_grid',cards:[{title:'Nytt kort',text:'Beskrivning'}]},qualityRules:['Minst ett kort']},
  notice:{label:'Meddelande',description:'Viktig information.',icon:'ph-info',category:'Text',variants:['info','warning','success'],defaultValue:{type:'notice',heading:'Viktigt',text:'Skriv meddelandet.',tone:'info'},qualityRules:['Rubrik krävs']},
  image_text:{label:'Bild och text',description:'Bild bredvid innehåll.',icon:'ph-columns',category:'Media',variants:['vänster','höger'],defaultValue:{type:'image_text',heading:'Ny rubrik',text:'Ny text',image:{src:'/images/smedby-area-overview.webp',alt:'Smedby 1:6'},imagePosition:'right'},qualityRules:['Alternativtext krävs']},
  link_list:{label:'Länklista',description:'En lista med säkra länkar.',icon:'ph-link',category:'Navigation',variants:['standard'],defaultValue:{type:'link_list',links:[{label:'Start',href:'/'}]},qualityRules:['Säkra länkar']},
  area_guide:{label:'Områdesguide',description:'Introduktion till området.',icon:'ph-map-trifold',category:'Media',variants:['standard'],defaultValue:{type:'area_guide',heading:'Om området',text:'Beskriv området.',links:[]},qualityRules:['Rubrik krävs']},
  faq:{label:'Frågor och svar',description:'Utfällbara svar.',icon:'ph-question',category:'Text',variants:['standard'],defaultValue:{type:'faq',items:[{question:'Ny fråga',answer:'Nytt svar'}]},qualityRules:['Fråga och svar krävs']},
  news_feed:{label:'Nyhetsflöde',description:'Publicerade nyheter.',icon:'ph-newspaper',category:'Dynamiskt innehåll',variants:['standard'],defaultValue:{type:'news_feed',heading:'Senaste nytt',limit:3},qualityRules:[]},
  calendar_feed:{label:'Kalenderflöde',description:'Kommande händelser.',icon:'ph-calendar',category:'Dynamiskt innehåll',variants:['standard'],defaultValue:{type:'calendar_feed',heading:'Kommande datum',limit:5},qualityRules:[]},
  document_list:{label:'Dokumentlista',description:'Publicerade dokument.',icon:'ph-files',category:'Dynamiskt innehåll',variants:['standard'],defaultValue:{type:'document_list',heading:'Dokument'},qualityRules:[]},
  search_teaser:{label:'Sök',description:'Sökfunktion med hjälptext.',icon:'ph-magnifying-glass',category:'Navigation',variants:['standard'],defaultValue:{type:'search_teaser',heading:'Sök på webbplatsen',text:'Hitta information.'},qualityRules:[]},
  heading:{label:'Rubrik',description:'Rubrik nivå 2 eller 3.',icon:'ph-text-h',category:'Text',variants:['h2','h3'],defaultValue:{type:'heading',level:2,text:'Ny rubrik'},qualityRules:['Ingen H1 i brödtext']},
  image:{label:'Bild',description:'Bild med fokuspunkt och alternativtext.',icon:'ph-image-square',category:'Media',variants:['original','square','landscape','portrait','wide'],defaultValue:{type:'image',image:{src:'/images/smedby-area-overview.webp',alt:'Smedby 1:6'}},qualityRules:['Alternativtext krävs']},
  button:{label:'Knapp',description:'Kontrollerad länkknapp.',icon:'ph-cursor-click',category:'Navigation',variants:['primary','secondary','text'],defaultValue:{type:'button',label:'Läs mer',href:'/',variant:'primary'},qualityRules:['Säker URL']},
  divider:{label:'Avdelare',description:'Visuell avdelare.',icon:'ph-minus',category:'Layout',variants:['subtle','strong'],defaultValue:{type:'divider',variant:'subtle'},qualityRules:[]},
  spacer:{label:'Mellanrum',description:'Fast kontrollerat mellanrum.',icon:'ph-arrows-out-line-vertical',category:'Layout',variants:['small','medium','large'],defaultValue:{type:'spacer',size:'medium'},qualityRules:[]},
  approved_embed:{label:'Godkänd inbäddning',description:'YouTube eller Vimeo i säker iframe.',icon:'ph-play-circle',category:'Media',variants:['16:9','4:3'],defaultValue:{type:'approved_embed',url:'https://www.youtube-nocookie.com/embed/',title:'Video',aspect:'16:9'},qualityRules:['Endast godkänd HTTPS-domän']},
};
